TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#DB += xxx.db
DB += mb-ai.db
DB += mb-ao.db
DB += mb-li.db
DB += mb-lo.db
DB += mb-bo.db
DB += mb-mbbo.db
#DB += mb-mbbi.db
DB += mb-cntrl-mode-mbbi.db 
DB += mb-cntrl-mode-mbbo.db 
DB += mb-count-mode-mbbi.db
DB += mb-count-mode-mbbo.db
DB += mb-reset-counter-mbbi.db
DB += mb-reset-mbbi.db
DB += mb-reset-mbbo.db
DB += mfc-control.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

