TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
DB += vacVersion.db
#DB += user.substitutions

DB += mb-ai.db
DB += mb-ao.db
DB += mb-li.db
DB += mb-lo.db
DB += mb-mbbo.db
#DB += mb-mbbi.db
DB += mb-cntrl-mode-mbbi.db 
DB += mb-cntrl-mode-mbbo.db 
DB += mb-count-mode-mbbi.db
DB += mb-count-mode-mbbo.db
DB += mb-reset-counter-mbbi.db
DB += mb-reset-mbbi.db
DB += mb-reset-mbbo.db
DB += mfc-control.db

#DB += bme680.db
#DB += bme680.proto
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

