TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
DB += vacVersion.db
#DB += dbSubExample.db
#DB += user.substitutions
DB += edwards-scu800.db
DB += edwards-scu800.proto
# DB += edwards-adc.db
# DB += edwards-adc.proto
DB += edwards-adc-analog.db
DB += edwards-adc-analog.proto

DB += edwards-gx-temp.db

DB += gate-valve.db
DB += gate-valve.proto
DB += armcontrol.db
DB += armcontrol.proto
DB += esther-states.db
#DB += mb-li.db
#DB += S7-eda-valve.db
#DB += S7-hva-valve.db
#DB += S7-tags.db
DB += S7-opcua.db
DB += S7-opcua-hva.db
DB += S7-opcua-eda.db
DB += nWRG.db
DB += nWRG.proto
# DB += pfeiffer.db
# DB += pfeiffer.proto
DB += thyracontV2.db
DB += thyracontV2.proto

#DB += bme680.db
#DB += bme680.proto
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

