TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
#DB += circle.db
#DB += dbExample1.db
#DB += dbExample2.db
DB += vacVersion.db
#DB += dbSubExample.db
#DB += user.substitutions
DB += edwards.db
DB += edwards.proto
DB += edwards-adc.db
DB += edwards-adc.proto

DB += armcontrol.db
DB += armcontrol.proto
DB += gate-valve.db
DB += gate-valve.proto
DB += estherStates.db

#DB += bme680.db
#DB += bme680.proto
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

