TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
#DB += circle.db
#DB += dbExample1.db
DB += vacVersion.db
#DB += user.substitutions
#DB += edwards-adc.proto

DB += mb-li.db

#DB += bme680.db
#DB += bme680.proto
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

